[package]
name = "module_rust"
version = "0.1.0"
authors = ["js <bada@ganada.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rulinalg = "0.4.2"
mnist = "0.4.0"
rand = "0.5.4"